# Generated by Django 4.2.29 on 2026-03-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests_text',
            field=models.CharField(blank=True, help_text='Comma-separated interests e.g. technology, sales, interviews', max_length=500),
        ),
    ]
