# Generated by Django 4.2.29 on 2026-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_userprofile_email_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='limit_minutes',
            field=models.IntegerField(default=300, help_text='Monthly practice minutes included'),
        ),
    ]
