# Generated by Django 4.2.29 on 2026-03-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_subscriptionplan_limit_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_minutes_reset_at',
            field=models.DateField(blank=True, help_text='Date when monthly minutes were last reset', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_minutes_used',
            field=models.IntegerField(default=0, help_text='Minutes spoken in current billing month'),
        ),
    ]
