# Generated by Django 4.2.29 on 2026-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_userprofile_monthly_minutes_reset_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_topic_date',
            field=models.DateField(blank=True, help_text='Date when daily topic was generated', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_topic_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_topic_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
