# Generated by Django 4.2.29 on 2026-03-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_userprofile_daily_topic_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='score_threshold',
            field=models.IntegerField(default=0, help_text='Minimum game_score required to earn this badge.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badge_level',
            field=models.CharField(choices=[('none', 'None'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='game_score',
            field=models.IntegerField(default=0, help_text='Gamified score from completed table topics'),
        ),
    ]
