# Generated by Django 4.2.29 on 2026-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_badge_score_threshold_userprofile_badge_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='badge_level',
            field=models.CharField(choices=[('none', 'None'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='bronze', max_length=20),
        ),
    ]
