# Generated by Django 4.2.29 on 2026-03-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkdocument',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='LinkDocument',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
