# Generated by Django 4.2.29 on 2026-03-15 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulate', '0002_remove_pdf_and_chat_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='What the user wants to practice (e.g. job interview, presentation).', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=20)),
                ('filler_words_count', models.IntegerField(blank=True, help_text='Count of um, uh, like, etc.', null=True)),
                ('pauses_count', models.IntegerField(blank=True, help_text='Number of noticeable pauses.', null=True)),
                ('speech_speed_wpm', models.FloatField(blank=True, help_text='Words per minute (user speech).', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Total conversation duration in seconds.', null=True)),
                ('rating', models.CharField(blank=True, choices=[('good', 'Good'), ('needs_work', 'Needs work'), ('poor', 'Poor')], help_text='Overall: good / needs_work / poor.', max_length=20, null=True)),
                ('feedback_summary', models.TextField(blank=True, help_text='Short feedback for the user on how to improve.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulate_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.IntegerField(default=0, help_text='Order of turn in conversation.')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='articulate.conversation')),
            ],
            options={
                'ordering': ['conversation', 'sequence'],
            },
        ),
    ]
