# Generated by Django 4.2.29 on 2026-03-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate', '0003_add_conversation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='filler_words_breakdown',
            field=models.JSONField(blank=True, help_text='Per-word filler count e.g. {"um": 5, "like": 3}.', null=True),
        ),
    ]
