# Generated by Django 4.2.29 on 2026-03-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate', '0004_add_filler_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='spoken_duration_seconds',
            field=models.FloatField(blank=True, help_text='Approx seconds user was speaking for this turn (mic-on time).', null=True),
        ),
    ]
