# Generated by Django 4.2.29 on 2026-03-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate', '0006_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Optional per-topic speaking time limit in seconds. Leave empty for default (3 minutes).', null=True),
        ),
    ]
