# Generated by Django 4.2.29 on 2026-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate', '0008_topicprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='last_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
